### PR TITLE
Fixed: potential arithmetic overflow in NTPPacket.getOffset()

### LINKED ISSUE #10: Swift runtime failure: arithmetic overflow in NTPPacket.getOffset(clientReceiveTime:)
We're using swift-ntp and have received the following crash report from our production environment. Unfortunately I don't have any reproducible cases or further logging to determine what's going wrong here, and this doesn't seem to be particularly widespread, but ideally the library could be made more resilient to cases such as this.

Our usage essentially equates to:
```
let ntp = NTPClient(
    config: NTPClient.Config(
        version: .v4
    ),
    server: "time.apple.com"
)
let response = try await ntp.query(timeout: SYNC_TIMEOUT)
```

```
EXC_BREAKPOINT: 

0  X +0x9dbd50          Swift runtime failure: arithmetic overflow (<compiler-generated>)
1  X +0x9dbd50          NTPPacket.getOffset(clientReceiveTime:) (NTPPacket.swift:134:29)
2  X +0x9117a0          specialized NTPHandler.channelRead(context:data:) (Handlers.swift:37:28)
3  X +0x9785a0          ChannelHandlerContext.invokeChannelRead(_:) (ChannelPipeline.swift:2095:28)
4  X +0x979e08          ChannelPipeline._fireChannelRead0(_:) (ChannelPipeline.swift:1018:29)
5  X +0x979e08          ChannelPipeline.SynchronousOperations.fireChannelRead(_:) (ChannelPipeline.swift:1482:28)
6  X +0xa5fe48          DatagramChannel.singleReadFromSocket(controlBytesBuffer:) (SocketChannel.swift:798:46)
7  X +0xa5f9b8          DatagramChannel.readFromSocket() (SocketChannel.swift:746:29)
8  X +0xa59534          specialized BaseSocketChannel.readable0()
9  X +0xa522f8          specialized BaseSocketChannel.readable() (BaseSocketChannel.swift:1129:14)
10 X +0xa522f8          specialized protocol witness for SelectableChannel.readable() in conformance BaseSocketChannel<A> (<compiler-generated>:1124:23)
11 X +0xa522f8          specialized SelectableEventLoop.handleEvent<A>(_:channel:) (SelectableEventLoop.swift:590:25)
12 X +0xa4ac8c          specialized SelectableEventLoop.handleEvent<A>(_:channel:) (<compiler-generated>)
13 X +0xa4ac8c          closure #1 in closure #2 in SelectableEventLoop.run() (SelectableEventLoop.swift:895:30)
14 X +0xa51a1c          thunk for @callee_guaranteed (@guaranteed SelectorEvent<NIORegistration>) -> (@error @owned Error) (<compiler-generated>)
15 X +0xa51a1c          partial apply for thunk for @callee_guaranteed (@guaranteed SelectorEvent<NIORegistration>) -> (@error @owned Error) (<compiler-generated>)
16 X +0xa4c4e0          specialized Selector.whenReady0(strategy:onLoopBegin:_:) (SelectorKqueue.swift:329:17)
17 X +0xa4a594          specialized Selector.whenReady(strategy:onLoopBegin:_:) (SelectorGeneric.swift:376:18)
18 X +0xa4a594          SelectableEventLoop._blockingWaitForWork(nextReadyDeadline:_:) (SelectableEventLoop.swift:814:28)
19 X +0xa47e0c          closure #2 in SelectableEventLoop.run() (SelectableEventLoop.swift:888:26)
20 X +0xa47e0c          specialized closure #1 in withAutoReleasePool<A>(_:) (SelectableEventLoop.swift:44:13)
21 X +0xa47e0c          specialized closure #1 in withAutoReleasePool<A>(_:) (<compiler-generated>)
22 X +0xa47e0c          $s10ObjectiveC15autoreleasepool8invokingq_q_yxYKXE_txYKs5ErrorRzRi__r0_lFsAD_p_xTi5yt_TG5 (<compiler-generated>)
23 X +0xa47e0c          specialized withAutoReleasePool<A>(_:) (SelectableEventLoop.swift:43:16)
24 X +0xa47e0c          SelectableEventLoop.run() (SelectableEventLoop.swift:887:17)
25 X +0xa12280          static MultiThreadedEventLoopGroup.runTheLoop(thread:uniqueID:parentGroup:canEventLoopBeShutdownIndividually:selectorFactory:initializer:metricsDelegate:_:) (MultiThreadedEventLoopGroup.swift:115:22)
26 X +0xa12280          closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:uniqueID:parentGroup:selectorFactory:initializer:metricsDelegate:) (MultiThreadedEventLoopGroup.swift:137:41)
27 X +0xa18a5c          partial apply for closure #1 in static MultiThreadedEventLoopGroup.setupThreadAndEventLoop(name:uniqueID:parentGroup:selectorFactory:initializer:metricsDelegate:) (<compiler-generated>)
28 X +0x7f9edc          thunk for @escaping @callee_guaranteed @Sendable (@guaranteed NSProgress) -> () (<compiler-generated>)
29 X +0xa6a8b8          closure #1 in closure #1 in static ThreadOpsPosix.run(handle:args:) (ThreadPosix.swift:172:21)
30 libsystem_pthread.dylib +0x4448 __pthread_start
```

### swift-ntp version/commit hash

swift-ntp 0.3.0 via SPM

### System & version information

Issue reported on iOS 26.0.1

### PR DESCRIPTION
**Pull request by agamdua**
Motivation:

Malformed NTP packets with large timestamp values can cause arithmetic overflow in the offset calculation, resulting in process crashes (EXC_BREAKPOINT).

Fixes #10

Modifications:

- added overflow checking in NTPPacket.getOffset()
- introduced package-level `_NTPError.arithmeticOverflow` for internal error handling
- added `NTPError.arithmeticOverflow` for surfacing it publicly.

Result:

Arithmetic overflow in offset calculations now throws instead of crashing, allowing applications to handle the errors instead of crashing.

### CODE REVIEW

File: Sources/NTPClient/NTPResponse.swift [hunk 1]
```diff
@@ -97,8 +97,16 @@ extension NTPResponse {
             throw NTPError.versionNotSupported
         }
 
+        // Catch _NTPError and convert to NTPError
+        let offset: TimeInterval
+        do {
+            offset = try p.getOffset(clientReceiveTime: clientReceiveTime)
+        } catch let e as _NTPError where e == .arithmeticOverflow {
+            throw NTPError.arithmeticOverflow
```
Comment (Lukasa) [inline Sources/NTPClient/NTPResponse.swift:105]: What's the benefit of the catch/rethrow dance

Comment (agamdua) [reply Sources/NTPClient/NTPResponse.swift:105]: we're translating the error form the internal `NTP` package to something that is consumable in the public API by consumers of the `NTPClient` package. this allows us to expose an arithmeticOverfllow without exposing details of the internal, underlying package

so its a throw type conversion rather than a re-throw

Comment (Lukasa) [reply Sources/NTPClient/NTPResponse.swift:105]: No, I get that.

My question is: why are we throwing `_NTPError` to begin with? It's brand new in this PR and has only one error case, which we have mapped to an also brand-new public error of the same name. Why not throw that error directly?

Comment (agamdua) [reply Sources/NTPClient/NTPResponse.swift:105]: `NTPError` is declared in the `NTPClient` at this time - so using that would create a circular dep where `NTP` package also depends on `NTPClient`, which we don't want.

This code translates between a the new error type only known to the internal `NTP` package `_NTPError` and the publicly available `NTPError` (from `NTPClient`).

**Review by Lukasa — APPROVED** [review]
